### ISSUE TITLE
Models flicker between rendered players in BTA 7.3

### ISSUE THREAD

**Issue by Aurailus** [tom5454/CustomPlayerModels#744]
Hey folks! We're encountering a really weird bug trying to use CPM on a legitimate (online mode) better than adventure 7.3 server. We've installed the mod on the server, and also on all of our clients, and when looking at some users it works fine, but for others the models behave really oddly. 

Working players that work show their model properly to all other accounts that work, so long as a non-working player isn't in the view frustum. Even a non-working player can see people's models fine in first person, but it breaks in third person. 

Non-working players for some reason seem to adopt one of the other players models when in the view frustum, causing the custom models of all players--working or otherwise--to shift to the wrong players. It's very odd. 

We've confirmed the following working accounts:
Aurailus
OtherAuri
Zythia_squeak

And the following non-working accounts:
DrawSage
deertailwag

We've tested both working and non-working accounts on different machines, OSs, and models, and it makes no difference. deertailwag always breaks the models if in view, no matter what the conditions, and OtherAuri never does. All of these accounts are legitimately owned Microsoft accounts. 

We're also getting force disconnected occasionally on server join / model change because of a host of different string errors, most commonly that a string is too long or of an invalid length. Not sure if that's related, we've just been ignoring it for now. 

We're using the latest CPM for BTA 7.3, and no other mods that would be likely to conflict.

**Comment by tom5454** [comment]
Please post your minecraft log, client and server logs.

**Comment by Aurailus** [comment]
Hey, created a minimum viable reproduction of the issue on a clean Babric server for 7.3.
Working user in this case: Aurailus. Broken user: Intics_

Server Debug Log: [debug.log](https://github.com/user-attachments/files/18630692/debug.log)
Server Latest Log: [latest.log](https://github.com/user-attachments/files/18630693/latest.log)

Client Debug Log: [debug.log](https://github.com/user-attachments/files/18630694/debug.log)
Client Latest Log: [latest.log](https://github.com/user-attachments/files/18630695/latest.log)

The full mods list on the server: CustomPlayerModels-BTA-0.6.19c.jar, halplibe-5.0.0.jar
The full mods list on the client: btalightoverlay-1.1.0-7.3.jar, CustomPlayerModels-BTA-0.6.19c.jar, halplibe-5.0.0.jar, modmenu-bta-3.0.0.jar, nofoodstack-1.0.1.jar

Reproduction video: 
![Video](https://i.imgur.com/MiAEMhK.gif)

**Comment by tom5454** [comment]
The debug.log file contains your access token, restart your launcher.

There is an animator error in the log, but that's a one time message.
I'll try to reproduce it locally.

**Comment by Aurailus** [comment]
Just a little update on this. We've been using Skin mode to bypass the weird string length issues which cause us to get disconnected on join, and we've found that that can cause the bug. Here's a new situation: I (Aurailus), have a skin with a model linked (first attachment) which seems to work fine. My friend (Zythia_squeak) _had_ a vanilla skin (second attachment), and was also working fine. But when he made a skin with a model linked (3rd link, if you look at the models they are based off the same file but not identical), his player being rendered caused the models to flip around *regardless* of if he was using the model from his skin or not. It seems like him simply having a model linked by his skin, even if he's not using it at the time, breaks things as well.

1. ![Aurailus Skin](https://github.com/user-attachments/assets/0c75803e-3836-4fcc-a006-97c66553c981)
2. ![Zythia's working vanilla skin](https://github.com/user-attachments/assets/018ad41f-1f9d-4ae0-8f60-b5b04d044b85)
3. ![Zythia's broken skin with a model linked](https://github.com/user-attachments/assets/7d19b986-8a4e-469d-a956-2ff727af8053)

**Comment by tom5454** [comment]
I fixed the model swapping issue, but I can't reproduce the disconnecting issue.
Can you send me the server log from when that happens and the client log?

**Comment by Aurailus** [comment]
Tysm!!! My friends and I really really love this mod, we really appreciate this ❤
I'll open a new issue for the disconnecting problem, and include logs.

Also, just an aside because I don't know how actively monitor BTA, 7.3_01 was published. It looks like it just requires changing the version in the manifest. Just thought I'd mention it in case you weren't aware: 
![Image](https://github.com/user-attachments/assets/8e748704-71b1-4af1-8d54-e71e1d85c4b9)

**Comment by Aurailus** [comment]
Just confirming the patch wasn't in the most recent update (0.6.20a)? I'm still getting the model swapping in that version downloaded from modrinth.

**Comment by tom5454** [comment]
No, it's going to be in the next update.
